project_name: dop-avm

# Define your build targets
builds:
- id: linux-amd64
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm64

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
  github:
    owner: devopspass
    name: dop-avm

dockers:
  - image_templates:
      - devopspass/ansible
